pipeline
        {
           agent any
           stages
          {
           stage("Git SCM")
                            {
                                steps
                                {
                                    git branch: 'main',
                                    credentialsId: 'GitHub_credentials',
                                    url: 'https://github.com/furkanevrenguzel/Temperature_Docker_BCF.me.git'
                                 }
                            }
          stage("Build")
          {
            agent
             {
                docker 
                {
                    image 'python:3.8'
                }
             }

            steps
            {
                sh "python -m compileall ."
            }
          }    
          stage("Test")
          {
            
            steps
            {
                echo "test"
            }
          }
          stage("Build Docker Image")
            {
            steps{
                sh "docker build -t furkanevrenguzel/api:latest ."
            }
        }
          stage ("Push dockerhub")
                 {
            steps
                {
                withCredentials([string(credentialsId: 'dockerpassid', variable: 'password')]) {
                    sh "docker login -u ********* -p **********"
                }
        
                sh "docker push furkanevrenguzel/api:latest"
            }
        }
         stage("Run Container")
         {
            steps
            {
                sh "docker run -v C:/WINDOWS/system32/config/systemprofile/AppData/Local/Jenkins/.jenkins/workspace/ -d -p 8080:8080 -p 50000:50000 --name bcf.me furkanevrenguzel/api:latest"
            }
        }
    }
}
